#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
sys.path.append('/usr/lib/clippy')
from application import CApplication

if __name__ == "__main__":
    app = CApplication()
    ret = app.run(sys.argv)
    sys.exit(ret)
