#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
from gi.repository import GObject
sys.path.append('/usr/lib/assistant/libclippy')
from fvp_application import FvpApplication


GObject.threads_init()

app = CApplication()
ret = app.run(sys.argv)
sys.exit(ret)
